### ISSUE TITLE
Spec STM boards

### ISSUE THREAD

**Issue by Matthew-501** [Dalhousie-Autonomous-Sailboat-Team/dalMAST#9]
Research STM MCU that supports our software/electrical requirements. 

Add broad recommendations to [this](https://docs.google.com/spreadsheets/d/10L90tp-SDlS_9h2VdWjhibj5wP3qvWc7q6kxsXtGO9E/edit#gid=0) spreadsheet

We need the following:

- Power Consumption ( 2.2 w/hr day )
-  1 I2C Port
-  7 UART
-  2 PWM
-  10 Bit-ADC

**Comment by ethanajohnston** [comment]
UART seems to be the reason why we wanted to switch.
What requires UART? GPS, Stream 211, Windvane, XBEE, debug/programming, maybe wireless sail control (might be using slip ring)
